### ISSUE TITLE
Les informations

### ISSUE THREAD

**Issue by Lomontrandsabert** [TeamFayBer/FayBerApp#42]
@ingdjason

![blood-20745_1920-1024x768](https://user-images.githubusercontent.com/30005382/30039657-b077ea54-91aa-11e7-872e-96b91922959f.jpg)
1- Info: Titre: LABORATOIRE 
Detail: Prélèvement et transfert de spécimen (sang, selles, urines, etc.) aux laboratoires.

![bandage-1235337_1920](https://user-images.githubusercontent.com/30005382/30039661-b9435e84-91aa-11e7-996a-147c967aebd8.jpg)
2- Info Titre: SOINS PANSEMENTS
Detail: Réalisation, surveillance et renouvellement de pansements.

![diabetes-528678_1920-1024x683](https://user-images.githubusercontent.com/30005382/30039663-be4292ec-91aa-11e7-8bb0-84ce63151125.jpg)
3- Info Titre: ASSISTANCE MEDICALE 
Detail:  Aide à la prise des médicaments présentés sous forme injectable et non injectable, surveillance de leurs effets  @secondaires.

![diabetes-877510_1920-1024x682](https://user-images.githubusercontent.com/30005382/30039664-c1832bce-91aa-11e7-8184-121f5135e4c0.jpg)
4- Info Titre: REALISATION DES TESTS
Dertails: Réalisation des tests rapides (malaria, hémogramme, glycémie, HIV, RPR, et autres.

![fitness-332278_1920-1024x680](https://user-images.githubusercontent.com/30005382/30039669-c6ae4d2c-91aa-11e7-8602-4aac443acf46.jpg)
5- Info Titre: HYGIENE CORPORELLE
Detail: Soins et procédés visant à assurer l’hygiène corporelle du patient/client et de son environnement.

![hands-770461_1920-1024x685](https://user-images.githubusercontent.com/30005382/30039671-cbf7cc04-91aa-11e7-9374-9972e95c6df5.jpg)
6- Info Titre: INSTALLATION DE SOLUTE & CATHETER
Detail: Installation de soluté, contrôle de la diurèse horaire et changement de sondes vésicales (Changement de cathéter).

![mental-health-2019924_1920-1024x682](https://user-images.githubusercontent.com/30005382/30039672-d264e0b8-91aa-11e7-80b5-d08efcbecaa9.jpg)
7- Info Titre: SOUTIEN PSYCHOLOGIQUE
Detail: Aide et soutien psychologique au besoin.

![tape-403593_1920-1024x681](https://user-images.githubusercontent.com/30005382/30039674-dce6d4c4-91aa-11e7-89c3-96ec843a4fb1.jpg)
8- Info Titre: SURVEILLANCE DES DIÈTES
Detail: Surveillance des diètes suivant l’ordonnance médicale.

![walker-1082410_1920-1024x768](https://user-images.githubusercontent.com/30005382/30039675-e4909188-91aa-11e7-9472-8ed5e0adfed0.jpg)
9- Info Titre: EDUCATION & REEDUCATION
Detail: Installation et éducation du patient/client par rapport à sa pathologie ou de son handicap.

**Comment by ingdjason** [comment]
Utiliser Library Picasso:(exemple)
{ img_liste --> from api}
url= http://fayberagency.com/v1/app/image_service/+img_liste;
Picasso.with(context).load(url).into(imageView);
